version: '3'

services:
  nginx:
    image: nginx:inception
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - vol_wordpress:/var/www/html
    networks:
      - net_inception
    ports:
      - 443:443

  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - vol_mariadb:/var/lib/mysql
    networks:
      - net_inception
    env_file:
      - .env

  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - vol_wordpress:/var/www/html
    networks:
      - net_inception
    env_file:
      - .env
    depends_on:
      - mariadb

volumes:
  vol_mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/tkong/data/mariadb
      o: bind

  vol_wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/tkong/data/wordpress
      o: bind

networks:
  net_inception:
    driver: bridge
